/* ZS.Fonts — brush-kai loading for a page that must survive file://
   (SANGUO-DESIGN.md §6.3).

   The chosen face is LXGW WenKai TC (霞鶩文楷, SIL OFL 1.1), shipped as an
   asset-time glyph subset rather than the ~15 MB full font.

   Two delivery paths, because a `@font-face` whose `src` is a file:// URL is a
   CORS-mode fetch from an opaque origin and browsers refuse it:

     served over http  ->  the @font-face rule in sanguo.html loads
                           fonts/lxgw-wenkai-tc.subset.woff2 normally
     double-clicked    ->  js/fonts/subset-data.js (generated by
                           tools/subset-font.py) assigns ZS.FONT_DATA_URL, a
                           data: URI, and the FontFace API loads that instead

   Both are attempted; whichever arrives wins, and the family name is the same
   either way so the CSS stack in sanguo.html keeps working. `ZS.Fonts.ok`
   reports whether real kai is on screen or the system fallback chain is doing
   the work. Nothing blocks boot on it. */
(() => {
  "use strict";
  const ZS = (window.ZS = window.ZS || {});

  const FAMILY = "LXGW WenKai TC";
  /* A string that must render in the subset. */
  const PROBE = "火柴三國";

  const Fonts = {
    FAMILY,
    ok: false,
    via: "fallback", // "data" | "css" | "fallback"
    error: null,

    async load() {
      let viaData = false;
      try {
        if (ZS.FONT_DATA_URL && typeof window.FontFace === "function") {
          const ff = new window.FontFace(FAMILY, "url(" + ZS.FONT_DATA_URL + ")");
          await ff.load();
          document.fonts.add(ff);
          viaData = true;
        }
      } catch (e) {
        this.error = String((e && e.message) || e);
      }
      try {
        /* Also nudge the CSS-declared face awake. It fails silently on file://
           (that is what the data: path is for) and is the normal route over
           http. Without this the face sits "unloaded" and never renders. */
        if (document.fonts && document.fonts.load) {
          await document.fonts.load('64px "' + FAMILY + '"', PROBE);
        }
        if (document.fonts && document.fonts.ready) await document.fonts.ready;
      } catch {
        /* An unreachable @font-face is not an error worth surfacing. */
      }

      this.ok = this.check();
      this.via = this.ok ? (viaData ? "data" : "css") : "fallback";
      document.documentElement.classList.toggle("font-kai", this.ok);
      return this.ok;
    },

    /* Rasterize the probe with the family, and again with only the generic
       default, and compare pixels.

       Width comparison does NOT work here: every CJK glyph in both the real
       face and every system fallback is exactly 1em wide, so the two measure
       identical. document.fonts.check() is also unreliable while a same-family
       @font-face rule sits unloaded beside the JS-added face. Pixels are the
       thing we actually care about anyway. */
    check() {
      const a = raster('64px "' + FAMILY + '"');
      const b = raster("64px serif");
      if (!a || !b || a.length !== b.length) return false;
      let diff = 0;
      for (let i = 3; i < a.length; i += 4) if (a[i] !== b[i]) diff++;
      /* A few hundred differing subpixels means a genuinely different outline;
         identical rasters mean the family fell through to the default. */
      return diff > 200;
    },
  };

  function raster(font) {
    try {
      const cv = document.createElement("canvas");
      cv.width = 288;
      cv.height = 80;
      const c = cv.getContext("2d");
      c.fillStyle = "#000";
      c.textBaseline = "alphabetic";
      c.font = font;
      c.fillText(PROBE, 4, 66);
      return c.getImageData(0, 0, cv.width, cv.height).data;
    } catch {
      return null;
    }
  }

  ZS.Fonts = Fonts;
})();
